import {PrismaClient} from "@/generated/prisma/client";


const jobTitles = [
    "Administrative and Asset Administrator",
    "Administrative Assistant",
    "Adjudicator",
    "Assistant Deputy Minister (ADM)",
    "Assistant Supervisor (ADS)",
    "Branch Coordinator",
    "Business Application Administrator",
    "Client Service Representative (CSR)",
    "Client Service Worker (CSW)",
    "Communications Analyst",
    "Communications and Engagement Analyst",
    "Community Integration Specialist",
    "Community Relations and Stakeholder Analyst",
    "Contract Analyst",
    "Contractor",
    "Data Analyst",
    "Director",
    "Director, Criminal Operations",
    "Director, Partnerships, Performance and Practice",
    "Director, Service Delivery",
    "Employment Assistance Worker",
    "Executive Administrative Assistant",
    "Executive Director",
    "Executive Director, Service Delivery",
    "Facilities and Assets Administrator",
    "Facilities and Assets Coordinator",
    "Financial Analyst",
    "Full Stack Developer",
    "Job Resources Analyst",
    "Job Resources Lead",
    "Junior Performance Analyst",
    "Junior Program Analyst",
    "Lead Trainer",
    "Major Case File Specialist",
    "Manager",
    "Manager, Business Technology Integration",
    "Manager, Community Relations and Service Quality",
    "Manager, Contracts",
    "Manager, Criminal Operations",
    "Manager, Data and Evaluation",
    "Manager, Facilities and Assets",
    "Manager, Financial Services",
    "Manager, Learning and Development",
    "Manager, Organizational Health and Development",
    "Manager, Partnerships and Practice",
    "Manager, Policy and Implementation Strategy",
    "Manager, Program Evaluation",
    "Manager, Program Evaluation and Reporting",
    "Manager, Program Integrity",
    "Manager, Recruitment",
    "Manager, SD and Program Development",
    "Manager, Senior Project",
    "Manager, Service Delivery",
    "Manager, Staffing",
    "Manager, Strategic Issues",
    "Manager, Strategic Planning and Projects",
    "Manager, Trainer Program",
    "Marketing Leader",
    "Ministry Investigator",
    "Operations Support Clerk",
    "Policy and Project Analyst",
    "Policy Interpretation and Coordination Analyst",
    "Process and Project Analyst",
    "Program and Policy Analyst",
    "Program Evaluation Specialist",
    "Program Specialist",
    "Program Support Clerk",
    "Program Support Supervisor",
    "Project Analyst",
    "Project Management Analyst",
    "Project Support Analyst",
    "Project Support Intern",
    "Quality and Compliance Specialist",
    "Records Clerk",
    "Records Management Supervisor",
    "Recruitment and Staffing Analyst",
    "Recruitment and Staffing Clerk",
    "Recruitment and Staffing Coordinator",
    "Research Analyst",
    "Research and Project Support",
    "Senior Budget Analyst",
    "Senior Business Analyst",
    "Senior Business Intelligence Analyst",
    "Senior Data Analyst",
    "Senior Data Architect",
    "Senior Data Architect and Data Scientist",
    "Senior Facilities and Assets Coordinator",
    "Senior Financial Contract Analyst",
    "Senior Investigator",
    "Senior Manager, Community Relations and Program Communication",
    "Senior Manager, Policy and Knowledge Management",
    "Senior Manager, Policy Interpretation and Implementation",
    "Senior Ministry Investigator",
    "Senior Policy and Program Specialist",
    "Senior Policy and Project Analyst",
    "Senior Policy and Project Specialist",
    "Senior Program Analyst",
    "Senior Project Management Advisor",
    "Senior Project Management Analyst",
    "Senior Records Management Analyst",
    "Supervisor, Administrative Services",
    "Supervisor, Criminal Investigations",
    "Supervisor, Prevention and Compliance",
    "Supervisor, Program Support",
    "Supervisor, Recruitment and Staffing",
    "Supervisor, Service Delivery",
    "Team Lead, Program Evaluation",
    "Trainer",
    "Training Coordinator",
    "Training Specialist",
    "Unit Administrator",
    "Workplace Health Advisor",
] as const

export async function seedJobTitles(prismaClient: PrismaClient) {

    await prismaClient.jobTitle.createMany({
        data: jobTitles.map(name => ({name}))
    })
}
