name: Deploy to production namespace

on:
  push:
    tags: ["v*"]

env:
  TOOLS_NS: a6d989-tools
  PROD_NS: a6d989-prod

  # BuildConfig name
  BUILD_APP: employee-information-database-prod

  # ImageStream name
  IMAGE_APP: employee-information-database

  # Deployment name
  DEPLOY_APP: employee-information-database

  REGISTRY: ${{ secrets.REGISTRY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "prod-deploy"
      cancel-in-progress: true

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "latest"

      - name: oc login
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OC_SERVER }}
          openshift_token: ${{ secrets.OC_TOKEN }} # SA token

      - name: Start OpenShift build in the tools namespace
        run: |
          # --wait flag tells the client to stream the build log and block until the build completes. It exits with a non-zero status if the build fails.
          oc start-build $BUILD_APP --wait -n $TOOLS_NS

      - name: Add custom tag to the newly created image in the tools namespace
        run: |
          # prod-<first7charsOfCommit>
          TAG=prod-${GITHUB_SHA::7}
          RELEASE_TAG=${GITHUB_REF_NAME}

          # prod-latest -> prod-<sha>-tools and prod-v<version>-tools
          oc -n $TOOLS_NS tag $IMAGE_APP:prod-latest \
            $IMAGE_APP:${TAG}-tools \
            $IMAGE_APP:prod-${RELEASE_TAG}-tools

          # save for later steps
          echo "IMAGE_TAG=${TAG}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV

      - name: Import this image in the production namespace and update the tag
        run: |
          oc -n $PROD_NS tag $TOOLS_NS/$IMAGE_APP:${IMAGE_TAG}-tools \
            $PROD_NS/$IMAGE_APP:${IMAGE_TAG}-prod \
            $PROD_NS/$IMAGE_APP:prod-${RELEASE_TAG}-prod

      - name: Update the deployment to use this new image
        run: |
          IMAGE=${REGISTRY}/${PROD_NS}/${IMAGE_APP}:${IMAGE_TAG}-prod
          oc -n $PROD_NS set image deployment/$DEPLOY_APP $DEPLOY_APP=$IMAGE

      - name: Wait for deployment to complete
        run: |
          oc -n $PROD_NS rollout status deployment/$DEPLOY_APP
